#!/usr/bin/env ruby

puts "Creating directories for config, backup, and swap..."

CONFIG_DIRECTORY = File.join(Dir.home,         ".config")
NVIM_DIRECTORY   = File.join(CONFIG_DIRECTORY, "nvim")
BACKUP_DIRECTORY = File.join(NVIM_DIRECTORY,   ".backup")
SWAP_DIRECTORY   = File.join(NVIM_DIRECTORY,   ".swap")

[NVIM_DIRECTORY, BACKUP_DIRECTORY, SWAP_DIRECTORY].each do |directory|
  Dir.mkdir(directory) unless File.exists?(directory)
end

puts "Installing neovim bindings for Python, Ruby, and Node..."

`pip3 install neovim`
`gem install neovim`
`npm install -g neovim`

puts "Setting up vim-plug for plugin management..."

VIM_PLUG_INSTALLATION_LOCATION = File.join(NVIM_DIRECTORY, "autoload", "plug.vim")
unless File.exists?(VIM_PLUG_INSTALLATION_LOCATION)
  `curl -fLo #{VIM_PLUG_INSTALLATION_LOCATION} --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim`
end

VIM_PLUG_PLUGINS_DIRECTORY = File.join(NVIM_DIRECTORY, "plugged")
Dir.mkdir(VIM_PLUG_PLUGINS_DIRECTORY) unless File.exists?(VIM_PLUG_PLUGINS_DIRECTORY)


puts "Setting up symlink for init.vim file..."

# ASSUMPTION: This script is being executed from within the dotfiles directory.
INIT_VIM_PATH = File.join(NVIM_DIRECTORY, "init.vim")
File.symlink(File.join(Dir.pwd, "init.vim"), INIT_VIM_PATH) unless File.exists?(INIT_VIM_PATH)

puts "Done. Open neovim and run :PlugInstall to install plugins."
