#!/usr/bin/env ruby

# Create directories, if they do not exist.
puts "Creating directories..."
CONFIG_DIRECTORY = File.join(Dir.home, ".config")
VIM_DIRECTORY = File.join(CONFIG_DIRECTORY, "vim")
BACKUP_DIRECTORY = File.join(VIM_DIRECTORY, ".backup")
SWAP_DIRECTORY   = File.join(VIM_DIRECTORY, ".swap")

[VIM_DIRECTORY, BACKUP_DIRECTORY, SWAP_DIRECTORY].each do |directory|
  Dir.mkdir(directory) unless File.exists?(directory)
end

# ASSUMPTION: This script is being executed from within the dotfiles directory.
puts "Symlinking vimrc file..."
VIMRC_PATH = File.join(Dir.home, ".vimrc")
File.symlink(File.join(Dir.pwd, ".vimrc"), VIMRC_PATH) unless File.exists?(VIMRC_PATH)

puts "Done."
